python3 icl.py --seed 42 --data sst2 --llm llama2_7b 
python3 icl.py --seed 41 --data sst2 --llm llama2_7b 
python3 icl.py --seed 40 --data sst2 --llm llama2_7b 
python3 icl.py --seed 39 --data sst2 --llm llama2_7b 
python3 icl.py --seed 38 --data sst2 --llm llama2_7b 
python3 icl.py --seed 42 --data sst5 --llm llama2_7b 
python3 icl.py --seed 41 --data sst5 --llm llama2_7b 
python3 icl.py --seed 40 --data sst5 --llm llama2_7b 
python3 icl.py --seed 39 --data sst5 --llm llama2_7b 
python3 icl.py --seed 38 --data sst5 --llm llama2_7b 
python3 icl.py --seed 42 --data trec --llm llama2_7b 
python3 icl.py --seed 41 --data trec --llm llama2_7b 
python3 icl.py --seed 40 --data trec --llm llama2_7b 
python3 icl.py --seed 39 --data trec --llm llama2_7b 
python3 icl.py --seed 38 --data trec --llm llama2_7b 
python3 icl.py --seed 42 --data subj --llm llama2_7b 
python3 icl.py --seed 41 --data subj --llm llama2_7b 
python3 icl.py --seed 40 --data subj --llm llama2_7b 
python3 icl.py --seed 39 --data subj --llm llama2_7b 
python3 icl.py --seed 38 --data subj --llm llama2_7b 
python3 icl.py --seed 42 --data CR --llm llama2_7b 
python3 icl.py --seed 41 --data CR --llm llama2_7b 
python3 icl.py --seed 40 --data CR --llm llama2_7b 
python3 icl.py --seed 39 --data CR --llm llama2_7b 
python3 icl.py --seed 38 --data CR --llm llama2_7b 
python3 icl.py --seed 42 --data agnews --llm llama2_7b 
python3 icl.py --seed 41 --data agnews --llm llama2_7b 
python3 icl.py --seed 40 --data agnews --llm llama2_7b 
python3 icl.py --seed 39 --data agnews --llm llama2_7b 
python3 icl.py --seed 38 --data agnews --llm llama2_7b 